absolute_path_of_pipeline_folder: /home/pipeline/

# Currated genes associated with resistance phenotype
# Can be a file as defined in mycobacterium/db/resistance_genes.csv or simply a list with the names of the genes
currated_genes: /home/pipeline/data/mycobacterium/db/resistance_genes.csv

#File listing currated genes for virulence factors, with uniprot accession number:
virulence_factors: /home/pipeline/data/staph/db/virulence_factors.tsv

#Ontology files from the card database. Should be changed to automatically fetch the files from the db

spec_for_mykrobe: tb
resistance_prediction_softwares: 
 - mykrobe
 - rgi

species: Mycobacterium tuberculosis
taxid: 1773

ref_ids_for_mapping: 
cov_cutoff: 5

phylogeny_image_size: 800

# Those file are specific to each analysis:

# If you wish to include samples from sras, list them in a tab separated file with the name of the sample and the sra accession number
sra_samples: example_sras.tsv

virulence_percentage_identity_cutoff: 80
virulence_coverage_cutoff: 70

# Read naming schemas:
# Read names must end with ".fastq" or ".fastq.gz" or ".fq" or ".fg.gz"
# The following regex must match the naming of your reads : 
# "(_L0+[0-9]+)?_(R)?(1|2)(_|.)" for paired reads. Otherwise your sample will be considered as single reads.
# Your sample name will be defined with every character before the regex "(_L0+[0-9]+)?_(R)?(1|2)"
# If you do not like this sample naming, create a tab seperated file with two columns, the first one with the sample naming previously defined and the second one with your desired names.
# Put this file on the folder where you will run snakemake and the sample_names value below should be the name of this file. 
# If wish to keep the automatic naming, set the value of this variable to empty

sample_names: example_sample_names.tsv


# Tab separated file with three columns: sample name (as automatically defined or according to your own sample naming file), genus, species
species_names_correspondance_file: example_species.tsv


#Internal pipeline parameters

#These are the parameters for read trimming 
minimum_quality_base: 35
minimum_read_length: 60
crop_to_read_length_from_end: 230

adapter_file_name: NexteraPE-PE.fa
adapter_removal_param1: 3
adapter_removal_param2: 25
adapter_removal_param3: 6




