publication: "'Submitted () to the INSDC'"

taxon_id_number: "36841"

#This is the taxonomic identification number of the species that was sequenced, that can be found in the Taxonomy Browser of the NCBI for instance. If the sequenced strain belongs to a new species, a new taxon id must be ask following the protocol available here : http://www.ebi.ac.uk/ena/submit/genomes-tax-id-requests

taxon_name: "'Terrisporobacter glycolicus 13042'"


EBI_project_number: "PRJEB22086"

#Project identification number of the EBI. The project must be registered beforehand according to http://www.ebi.ac.uk/ena/submit/project-format on the Webin interface of the genome


description_of_the_genome_sequence: "'A genome'"


authors: ["Opota O", "Laurent S", "Greub G"]

translation_table: "11"


prefix_locus_tag: "TERRISP13"

#This is the prefix of the locus tag for each genes. They have to be book from EBI-ENA and this can be done during the project registration