sample_naming_type: molis
sample_names: sample_names.tsv
spec_for_mykrobe: tb
resistance_prediction_softwares: 
 - mykrobe
 - rgi

species: Mycobacterium tuberculosis
taxid: 1773

ref_ids_for_mapping: 
cov_cutoff: 5
snps_distance_threshold: 15

species_names_correspondance_file: species.csv

currated_genes: /home/sacha/Documents/new_strain/mycobacterium/db/resistance_genes.csv

ontology_file_aro: aro.obo
ontology_file_mo: mo.obo
ontology_file_ro: ro.obo


#Internal pipeline parameters

#These are the parameters for read trimming 
minimum_quality_base: 35
minimum_read_length: 60
crop_at_read_beginning: 10




