name: new_strain_assembly
channels:
 - bioconda
 - conda-forge
dependencies:
 - spades = 3.10.1
 - fastqc = 0.11.5
 - trimmomatic = 0.36
 - quast = 4.5
 - entrez-direct = 7.00
 - gff3toembl = 1.1.4
 - embl-api-validator = 1.1.173
 - prokka = 1.11

