name: new_strain
channels:
 - bioconda
 - conda-forge
dependencies:
 - python = 2.7
 - perl = 5.22.0
 - spades = 3.10.1
 - fastqc = 0.11.5
 - trimmomatic = 0.36
 - quast = 4.5
 - entrez-direct = 5.80
 - biopython = 1.70
 - orthofinder = 1.1.4